image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
vscode:
  extensions:
    - naumovs.color-highlight@2.3.0:6nKORbxgnWjNaN6xACiaQQ==
    - esbenp.prettier-vscode@5.1.3:t532ajsImUSrA9N8Bd7jQw==
    - msjsdiag.debugger-for-chrome@4.12.6:IdQBlCQEnixzHAOkHC36ew==
    - ritwickdey.LiveServer@5.6.1:wV4LBkq6Z5s1xwf2HrB+cw==
    - humao.rest-client@0.24.1:ggeyvIVSWsjotnh1tr2HMw==
    - WallabyJs.quokka-vscode@1.0.312:Tm1xSg4Ny48Gd8AHf1SJNg==